# Generated by Django 4.2.11 on 2025-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seeker', 'job seeker'), ('poster', 'job poster')], default='seeker', max_length=10),
        ),
    ]
